### ISSUE TITLE
Print only one information from a webscraping

### ISSUE THREAD

**Issue by JoaoBarcellos9** [JoaoBarcellos9/python#1]
Hello, I´m new on this site and new on programming, following some tutorials I coded something to try to make a robot to place bets, I am using webcsraping to get the latest results from the site, but I need to isolate only one element from the webscraping, currently my code is giving all this informations:
[{"id":"w1Da7OLLkE","created_at":"2023-02-09T01:58:21.470Z","color":1,"roll":6,"server_seed":"c319ddbada0d7443db465fa792fd4ac4a3826d8bc0a9eb9bebef48845a59d8b8"}...
I want to print only the element "color"

My code:
import requests

url = "https://blaze.com/api/roulette_games/recent"

payload = ""
headers = {
    "authority": "blaze.com",
    "accept": "application/json, text/plain, */*",
    "accept-language": "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
    "cookie": "_ga=GA1.2.2056275379.1639870302; _gid=GA1.2.1772014635.1675822552; __zlcmid=1EKlaNcDT5iT24X; _gat=1",
    "referer": "https://blaze.com/pt/games/double",
    "sec-ch-ua-mobile": "?0",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "sec-gpc": "1",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
    "x-client-language": "pt",
    "x-client-version": "c4e930377"
}

response = requests.request("GET", url, data=payload, headers=headers)
print(response.text)

#python #webscraping

**Comment by mdanok** [comment]
Hello,
you can access it with **json()**, like this:
`print(response.json())`

or if you can you can write it like this:
`some_json_data = json.loads(response.text)`

**Comment by JoaoBarcellos9** [comment]
ok thank you, it helped :)
